# tomcat
server:
  port: 9100
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    # 最大线程数
    max-threads: 1000
    max-http-header-size: 8096
    # 设置tomcat的basedir
    basedir: ${user.home}/tomcat/tmps
    # 最大连接数
    max-connections: 2000
  servlet:
    context-path: /pms-admin
    
# spring
spring:
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: /pms-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 如果使用字符串表示，用这行设置格式
    defaultPropertyInclusion: ALWAYS # 如果传递过来的时间为空则不进行过滤
    timezone: GMT+8
    serialization:
      write-dates-as-timestamps: false # 使用时间戳，使用数值timestamp表示日期
      # 数据库访问配置
  datasource:
     name: mysql
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://101.201.67.138:3306/oauth_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
     username: root
     password: wind2@
     max-idle: 10
     max-wait: 10000
     min-idle: 5
     initial-size: 5
     # 德鲁伊连接池的补充设置，应用到上面所有数据源中
     initialSize: 5
     minIdle: 5
     maxActive: 20
     # 配置获取连接等待超时的时间
     maxWait: 60000
     # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
     timeBetweenEvictionRunsMillis: 60000
     # 配置一个连接在池中最小生存的时间，单位是毫秒
     minEvictableIdleTimeMillis: 300000
     validationQuery: SELECT 1 FROM DUAL
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
     filters: stat,wall,log4j
     logSlowSql: true
  #redis config
  redis:
    host: 192.168.1.151 #101.201.67.138
    port: 6379
    password: wind2@ # 如果未单独配置默认为空即可
    timeout: 3000
    database: 7
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
        
#security无需要保护的资源路径        
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /dingtalk/dingtalkCallback
      - /app/dingtalkCallback
             
#security jwt（校验jwt签名）
jwt:
  cert-info:
    # 公钥证书存放位置
    public-key-location: myjks.cer
  claims:
    # 令牌的鉴发方：即授权服务器的地址
    issuer: http://os.com:9000/pms-auth-server       

#Dingding扫码配置
dingtalk:
  
  #企业内部微应用/小程序
  appKey: "dingqrb61fohwuxecdmh"
  appKeySecret: "dpgbe0fZRPqfV4DpnMewvdcXJeSMsojN2lNG_7DYSIpeLYnXDiw220pGt632MHYW"
  #企业内部应用
  appId: "ding0xpwlxnnlt2pnuqn"
  appSecret: "7CvQ383toWdeSRf8C7Gatp4ot-O-Sc_eAf2VOdqn3GS1qU3Ca4A0AvAtMexkEFrf"
  getTokenUrl: "https://oapi.dingtalk.com/gettoken"
  getAppUserInfoUrl: "https://oapi.dingtalk.com/user/getuserinfo"
  getUserInfoUrl: "https://oapi.dingtalk.com/sns/getuserinfo_bycode"
  getUnionIdUrl: "https://oapi.dingtalk.com/topapi/user/getbyunionid"
  getUserByUserIdUrl: "https://oapi.dingtalk.com/topapi/v2/user/get"
           
# 日志
logging:
  level:
    root: DEBUG
  config: classpath:log/logback-spring-dev.xml
